### ISSUE TITLE
Youtube-Vimeo-Video-Downloader-Script

### ISSUE THREAD

**Issue by sahibkhan** [sauryaacharya/Youtube-Vimeo-Video-Downloader-Script#2]
how we can use that my script print like that but i don't know how its work

Array ( [0] => Array ( [url] => https://r3---sn-o5t5uxa-pncl.googlevideo.com/videoplayback?expire=1488457574&pl=24&requiressl=yes&ip=203.99.59.234&id=o-AOyoEacCUttSPhztEevrzUuFuqGLKGMQNwWU160deSNh&ratebypass=yes&initcwndbps=857500&source=youtube&mm=31&mn=sn-o5t5uxa-pncl&upn=XBscf3E_Q_Q&sparams=ctier%2Cdur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&ctier=L&dur=441.875&mt=1488435866&mv=m&ms=au&mime=video%2Fmp4&itag=22&key=yt6&ipbits=0&lmt=1471453608175062&signature=8E3BA8F99549EE20F49C70B3F001E924E63E8326.9BD0ED357AF04C958C0B256D401A7BB07356F039&beids=%5B9452307%5D [itag] => 22 [fallback_host] => redirector.googlevideo.com [quality] => hd720 [title] => Eminem - Phenomenal [mime] => video/mp4 [format] => mp4 ) [1] => Array ( [url] => https://r3---sn-o5t5uxa-pncl.googlevideo.com/videoplayback?expire=1488457574&pl=24&requiressl=yes&ip=203.99.59.234&id=o-AOyoEacCUttSPhztEevrzUuFuqGLKGMQNwWU160deSNh&ratebypass=yes&initcwndbps=857500&source=youtube&mm=31&mn=sn-o5t5uxa-pncl&upn=XBscf3E_Q_Q&sparams=ctier%2Cdur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&ctier=L&dur=0.000&mt=1488435866&mv=m&ms=au&mime=video%2Fwebm&itag=43&key=yt6&ipbits=0&lmt=1443656384288815&signature=56829B081F7D71661FF6D4588B1B0FA70EF4BAB5.A6E84E8789A7CBEE3363F3C9010F445B586F28DF&beids=%5B9452307%5D [itag] => 43 [fallback_host] => redirector.googlevideo.com [quality] => medium [title] => Eminem - Phenomenal [mime] => video/webm [format] => webm ) [2] => Array ( [url] => https://r3---sn-o5t5uxa-pncl.googlevideo.com/videoplayback?expire=1488457574&pl=24&requiressl=yes&ip=203.99.59.234&id=o-AOyoEacCUttSPhztEevrzUuFuqGLKGMQNwWU160deSNh&ratebypass=yes&initcwndbps=857500&source=youtube&mm=31&mn=sn-o5t5uxa-pncl&upn=XBscf3E_Q_Q&sparams=ctier%2Cdur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&ctier=L&dur=441.875&mt=1488435866&mv=m&ms=au&mime=video%2Fmp4&itag=18&key=yt6&ipbits=0&lmt=1458222356122836&signature=56EBBCCE4B0DBE440CB7B62890219EB717502461.DD510EFD6761F76FEE4D685447163EC26EA693E9&beids=%5B9452307%5D [itag] => 18 [fallback_host] => redirector.googlevideo.com [quality] => medium [title] => Eminem - Phenomenal [mime] => video/mp4 [format] => mp4 ) [3] => Array ( [url] => https://r3---sn-o5t5uxa-pncl.googlevideo.com/videoplayback?source=youtube&mm=31&mn=sn-o5t5uxa-pncl&upn=XBscf3E_Q_Q&expire=1488457574&ctier=L&pl=24&requiressl=yes&dur=441.922&mt=1488435866&mv=m&ms=au&ip=203.99.59.234&mime=video%2F3gpp&itag=36&key=yt6&ipbits=0&lmt=1443655535935123&signature=16945FA28AED96553DB10AE8ED3FD8DA041202C9.B2FCC517A6A6C2492506E636581C0B05DD494E94&id=o-AOyoEacCUttSPhztEevrzUuFuqGLKGMQNwWU160deSNh&sparams=ctier%2Cdur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&initcwndbps=857500&beids=%5B9452307%5D [itag] => 36 [fallback_host] => redirector.googlevideo.com [quality] => small [title] => Eminem - Phenomenal [mime] => video/3gpp [format] => 3gpp ) [4] => Array ( [url] => https://r3---sn-o5t5uxa-pncl.googlevideo.com/videoplayback?source=youtube&mm=31&mn=sn-o5t5uxa-pncl&upn=XBscf3E_Q_Q&expire=1488457574&ctier=L&pl=24&requiressl=yes&dur=441.922&mt=1488435866&mv=m&ms=au&ip=203.99.59.234&mime=video%2F3gpp&itag=17&key=yt6&ipbits=0&lmt=1443655534230741&signature=7497588FBC541FA54F7ACC62E900120FA0860E36.75F2118772DE179F1A357394DEF956BC735A456B&id=o-AOyoEacCUttSPhztEevrzUuFuqGLKGMQNwWU160deSNh&sparams=ctier%2Cdur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&initcwndbps=857500&beids=%5B9452307%5D [itag] => 17 [fallback_host] => redirector.googlevideo.com [quality] => small [title] => Eminem - Phenomenal [mime] => video/3gpp [format] => 3gpp ) )

**Comment by sauryaacharya** [comment]
These are the url where the original videos are located. You can make your own downloader extracting url from that array.
